#%RAML 1.0 Trait

    description: This trait defines the parameters that are used to paginate a collection.
    queryParameters:
      offset?:
        description: The first entry to return from a collection.
        type: integer
        required: false
        default: 0
      limit?:
        description: The number of entries to return.
        type: integer
        required: false
        default: 20
      page?:
        description: The page of results to return.
        type: integer
        required: false
        default: 1