#%RAML 1.0 NamedExample
patientexample:
  {
               "patientId": "p01",
               "name": "Kebede",
               "age": 32,
               "address": "Addis Ababa",
               "gender": "Male"
              }