#%RAML 1.0 NamedExample

   [
            {
               "patientId": "p01",
               "name": "Kebede",
               "age": 32,
               "address": "Addis Ababa",
               "gender": "Male"
            },
            {
               "patientId": "p02",
               "name": "Chaltu",
               "age": 42,
               "address": "Bishoftu",
               "gender": "Female"
            }
            ]