#%RAML 1.0 NamedExample
 {
                "patientId": "p04",
                "name": "Gatoch Samuel",
                "age": 72,
                "email": "gatoch@gmail.com",
                "phone": "+251-9-88-90-23-45",
                "gender": "male",
                 "address": {
                  "Country": "Ethiopia",
                  "City": "Adama",
                  "Street": "Menahiriya"
                },
                "room_service": true
              }