#%RAML 1.0 NamedExample
[
                {
                  "id": 1,
                  "name": "Lisinopril",
                  "dosage": "10mg"
                },
                {
                  "id": 2,
                  "name": "Metformin",
                  "dosage": "20mg"
                }
              ]