#%RAML 1.0 NamedExample
 [{
                "patientId": "p01",
                "name": "Kebede Alemu",
                "age": 32,
                "email": "kebede@gmail.com",
                "phone": "+251-9-41-01-71-98",
                "gender": "male",
                 "address": {
                  "Country": "Ethiopia",
                  "City": "Addis Ababa",
                  "Street": "Bole"
                },
                "room_service": true
              },
              {
                "patientId": "p02",
                "name": "Selamawit Abreham",
                "age": 22,
                "email": "selamawit@gmail.com",
                "phone": "+251-9-72-18-53-34",
                "gender": "female",
                 "address": {
                  "Country": "Ethiopia",
                  "City": "Arbaminch",
                  "Street": "Hayq"
                },
                "room_service": false
              },
              {
                "patientId": "p03",
                "name": "Chala Hagos",
                "age": 28,
                "email": "chala@gmail.com",
                "phone": "+251-9-23-90-87-22",
                "gender": "male",
                 "address": {
                  "Country": "Ethiopia",
                  "City": "Debremarkos",
                  "Street": "Abima"
                },
                "room_service": false
              },
              {
                "patientId": "p04",
                "name": "Gatoch Samuel",
                "age": 72,
                "email": "gatoch@gmail.com",
                "phone": "+251-9-88-90-23-45",
                "gender": "male",
                 "address": {
                  "Country": "Ethiopia",
                  "City": "Adama",
                  "Street": "Menahiriya"
                },
                "room_service": true
              }]